// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master/proto/master.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type G_Master_Role struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G_Master_Role) Reset()         { *m = G_Master_Role{} }
func (m *G_Master_Role) String() string { return proto.CompactTextString(m) }
func (*G_Master_Role) ProtoMessage()    {}
func (*G_Master_Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2be617c45cb882, []int{0}
}

func (m *G_Master_Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G_Master_Role.Unmarshal(m, b)
}
func (m *G_Master_Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G_Master_Role.Marshal(b, m, deterministic)
}
func (m *G_Master_Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G_Master_Role.Merge(m, src)
}
func (m *G_Master_Role) XXX_Size() int {
	return xxx_messageInfo_G_Master_Role.Size(m)
}
func (m *G_Master_Role) XXX_DiscardUnknown() {
	xxx_messageInfo_G_Master_Role.DiscardUnknown(m)
}

var xxx_messageInfo_G_Master_Role proto.InternalMessageInfo

type Role struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ModelId              int32    `protobuf:"varint,2,opt,name=modelId,proto3" json:"modelId,omitempty"`
	ModelLv              int32    `protobuf:"varint,3,opt,name=modelLv,proto3" json:"modelLv,omitempty"`
	Cup                  int32    `protobuf:"varint,4,opt,name=cup,proto3" json:"cup,omitempty"`
	Uname                string   `protobuf:"bytes,5,opt,name=uname,proto3" json:"uname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2be617c45cb882, []int{1}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Role) GetModelId() int32 {
	if m != nil {
		return m.ModelId
	}
	return 0
}

func (m *Role) GetModelLv() int32 {
	if m != nil {
		return m.ModelLv
	}
	return 0
}

func (m *Role) GetCup() int32 {
	if m != nil {
		return m.Cup
	}
	return 0
}

func (m *Role) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func init() {
	proto.RegisterType((*G_Master_Role)(nil), "master_pb.G_Master_Role")
	proto.RegisterType((*Role)(nil), "master_pb.Role")
}

func init() { proto.RegisterFile("master/proto/master.proto", fileDescriptor_db2be617c45cb882) }

var fileDescriptor_db2be617c45cb882 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x4d, 0x2c, 0x2e,
	0x49, 0x2d, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x87, 0x70, 0xf4, 0xc0, 0x1c, 0x21, 0x4e,
	0x08, 0x2f, 0xbe, 0x20, 0x49, 0x89, 0x9f, 0x8b, 0xd7, 0x3d, 0xde, 0x17, 0xc2, 0x0d, 0xca, 0xcf,
	0x49, 0x55, 0x2a, 0xe1, 0x62, 0x01, 0xd1, 0x42, 0x02, 0x5c, 0xcc, 0xa5, 0x99, 0x29, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x20, 0xa6, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x7e, 0x4a, 0x6a, 0x8e,
	0x67, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x8c, 0x0b, 0x97, 0xf1, 0x29, 0x93, 0x60,
	0x46, 0x92, 0xf1, 0x29, 0x03, 0x99, 0x92, 0x5c, 0x5a, 0x20, 0xc1, 0x02, 0x16, 0x05, 0x31, 0x85,
	0x44, 0xb8, 0x58, 0x4b, 0xf3, 0x12, 0x73, 0x53, 0x25, 0x58, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20,
	0x1c, 0x27, 0x8d, 0x28, 0xb5, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd,
	0x8c, 0xcc, 0xc4, 0xbc, 0x6c, 0xfd, 0x92, 0x8c, 0xcc, 0xbc, 0xec, 0xd4, 0xbc, 0x14, 0x7d, 0x64,
	0x8f, 0x24, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xd1, 0xb0, 0xe2,
	0xdf, 0x00, 0x00, 0x00,
}
