apiVersion: v1
kind: Service
metadata:
  name: master-service
  namespace: think
spec:
  type: NodePort
  ports:
  - name: grpc
    protocol: TCP
    port: 8026
    targetPort: 8026
  - name: ws
    port: 8022
    targetPort: 8022
    protocol: TCP
    nodePort: 30250
  selector:
    app: think-master
