// Code generated by protoc-gen-go. DO NOT EDIT.
// source: war/proto/war.proto

package war_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	proto1 "github.com/hiank/thinkend/master/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type War_Type int32

const (
	War_Type_NIL        War_Type = 0
	War_Type_SOCCER     War_Type = 1
	War_Type_ONEWINNER  War_Type = 2
	War_Type_TEAMWINNER War_Type = 3
	War_Type_HUNTING    War_Type = 4
)

var War_Type_name = map[int32]string{
	0: "NIL",
	1: "SOCCER",
	2: "ONEWINNER",
	3: "TEAMWINNER",
	4: "HUNTING",
}

var War_Type_value = map[string]int32{
	"NIL":        0,
	"SOCCER":     1,
	"ONEWINNER":  2,
	"TEAMWINNER": 3,
	"HUNTING":    4,
}

func (x War_Type) String() string {
	return proto.EnumName(War_Type_name, int32(x))
}

func (War_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{0}
}

//S_War_Want 想要战斗
type S_War_Want struct {
	Type                 War_Type `protobuf:"varint,1,opt,name=type,proto3,enum=war_pb.War_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S_War_Want) Reset()         { *m = S_War_Want{} }
func (m *S_War_Want) String() string { return proto.CompactTextString(m) }
func (*S_War_Want) ProtoMessage()    {}
func (*S_War_Want) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{0}
}

func (m *S_War_Want) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S_War_Want.Unmarshal(m, b)
}
func (m *S_War_Want) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S_War_Want.Marshal(b, m, deterministic)
}
func (m *S_War_Want) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S_War_Want.Merge(m, src)
}
func (m *S_War_Want) XXX_Size() int {
	return xxx_messageInfo_S_War_Want.Size(m)
}
func (m *S_War_Want) XXX_DiscardUnknown() {
	xxx_messageInfo_S_War_Want.DiscardUnknown(m)
}

var xxx_messageInfo_S_War_Want proto.InternalMessageInfo

func (m *S_War_Want) GetType() War_Type {
	if m != nil {
		return m.Type
	}
	return War_Type_NIL
}

//S_War_Do 执行操作
type S_War_Do struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action               *any.Any `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S_War_Do) Reset()         { *m = S_War_Do{} }
func (m *S_War_Do) String() string { return proto.CompactTextString(m) }
func (*S_War_Do) ProtoMessage()    {}
func (*S_War_Do) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{1}
}

func (m *S_War_Do) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S_War_Do.Unmarshal(m, b)
}
func (m *S_War_Do) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S_War_Do.Marshal(b, m, deterministic)
}
func (m *S_War_Do) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S_War_Do.Merge(m, src)
}
func (m *S_War_Do) XXX_Size() int {
	return xxx_messageInfo_S_War_Do.Size(m)
}
func (m *S_War_Do) XXX_DiscardUnknown() {
	xxx_messageInfo_S_War_Do.DiscardUnknown(m)
}

var xxx_messageInfo_S_War_Do proto.InternalMessageInfo

func (m *S_War_Do) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S_War_Do) GetAction() *any.Any {
	if m != nil {
		return m.Action
	}
	return nil
}

type Team struct {
	Roles                []*proto1.Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{2}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetRoles() []*proto1.Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type War_Match struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MapId                int32    `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
	League               []*Team  `protobuf:"bytes,3,rep,name=league,proto3" json:"league,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *War_Match) Reset()         { *m = War_Match{} }
func (m *War_Match) String() string { return proto.CompactTextString(m) }
func (*War_Match) ProtoMessage()    {}
func (*War_Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{3}
}

func (m *War_Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_War_Match.Unmarshal(m, b)
}
func (m *War_Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_War_Match.Marshal(b, m, deterministic)
}
func (m *War_Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_War_Match.Merge(m, src)
}
func (m *War_Match) XXX_Size() int {
	return xxx_messageInfo_War_Match.Size(m)
}
func (m *War_Match) XXX_DiscardUnknown() {
	xxx_messageInfo_War_Match.DiscardUnknown(m)
}

var xxx_messageInfo_War_Match proto.InternalMessageInfo

func (m *War_Match) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *War_Match) GetMapId() int32 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *War_Match) GetLeague() []*Team {
	if m != nil {
		return m.League
	}
	return nil
}

//Tick 服务器定期下发，用于同步表现
type Tick struct {
	Index                int32      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Actions              []*any.Any `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Tick) Reset()         { *m = Tick{} }
func (m *Tick) String() string { return proto.CompactTextString(m) }
func (*Tick) ProtoMessage()    {}
func (*Tick) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{4}
}

func (m *Tick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tick.Unmarshal(m, b)
}
func (m *Tick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tick.Marshal(b, m, deterministic)
}
func (m *Tick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tick.Merge(m, src)
}
func (m *Tick) XXX_Size() int {
	return xxx_messageInfo_Tick.Size(m)
}
func (m *Tick) XXX_DiscardUnknown() {
	xxx_messageInfo_Tick.DiscardUnknown(m)
}

var xxx_messageInfo_Tick proto.InternalMessageInfo

func (m *Tick) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Tick) GetActions() []*any.Any {
	if m != nil {
		return m.Actions
	}
	return nil
}

//DecimalVector3 向量数据结构
type DecimalVector3 struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    string   `protobuf:"bytes,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecimalVector3) Reset()         { *m = DecimalVector3{} }
func (m *DecimalVector3) String() string { return proto.CompactTextString(m) }
func (*DecimalVector3) ProtoMessage()    {}
func (*DecimalVector3) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{5}
}

func (m *DecimalVector3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecimalVector3.Unmarshal(m, b)
}
func (m *DecimalVector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecimalVector3.Marshal(b, m, deterministic)
}
func (m *DecimalVector3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecimalVector3.Merge(m, src)
}
func (m *DecimalVector3) XXX_Size() int {
	return xxx_messageInfo_DecimalVector3.Size(m)
}
func (m *DecimalVector3) XXX_DiscardUnknown() {
	xxx_messageInfo_DecimalVector3.DiscardUnknown(m)
}

var xxx_messageInfo_DecimalVector3 proto.InternalMessageInfo

func (m *DecimalVector3) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *DecimalVector3) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *DecimalVector3) GetZ() string {
	if m != nil {
		return m.Z
	}
	return ""
}

//Move 移动操作，记录当前tick中移动属性
type Move struct {
	Uid                  uint64          `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Speed                *DecimalVector3 `protobuf:"bytes,2,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{6}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Move) GetSpeed() *DecimalVector3 {
	if m != nil {
		return m.Speed
	}
	return nil
}

//Shoot 射击操作
type Shoot struct {
	Uid                  uint64          `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Super                bool            `protobuf:"varint,2,opt,name=super,proto3" json:"super,omitempty"`
	Point                *DecimalVector3 `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Shoot) Reset()         { *m = Shoot{} }
func (m *Shoot) String() string { return proto.CompactTextString(m) }
func (*Shoot) ProtoMessage()    {}
func (*Shoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15f2f0457f888da, []int{7}
}

func (m *Shoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shoot.Unmarshal(m, b)
}
func (m *Shoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shoot.Marshal(b, m, deterministic)
}
func (m *Shoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shoot.Merge(m, src)
}
func (m *Shoot) XXX_Size() int {
	return xxx_messageInfo_Shoot.Size(m)
}
func (m *Shoot) XXX_DiscardUnknown() {
	xxx_messageInfo_Shoot.DiscardUnknown(m)
}

var xxx_messageInfo_Shoot proto.InternalMessageInfo

func (m *Shoot) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Shoot) GetSuper() bool {
	if m != nil {
		return m.Super
	}
	return false
}

func (m *Shoot) GetPoint() *DecimalVector3 {
	if m != nil {
		return m.Point
	}
	return nil
}

func init() {
	proto.RegisterEnum("war_pb.War_Type", War_Type_name, War_Type_value)
	proto.RegisterType((*S_War_Want)(nil), "war_pb.S_War_Want")
	proto.RegisterType((*S_War_Do)(nil), "war_pb.S_War_Do")
	proto.RegisterType((*Team)(nil), "war_pb.Team")
	proto.RegisterType((*War_Match)(nil), "war_pb.War_Match")
	proto.RegisterType((*Tick)(nil), "war_pb.Tick")
	proto.RegisterType((*DecimalVector3)(nil), "war_pb.DecimalVector3")
	proto.RegisterType((*Move)(nil), "war_pb.Move")
	proto.RegisterType((*Shoot)(nil), "war_pb.Shoot")
}

func init() { proto.RegisterFile("war/proto/war.proto", fileDescriptor_c15f2f0457f888da) }

var fileDescriptor_c15f2f0457f888da = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x6b, 0xdb, 0x30,
	0x14, 0xc5, 0xe7, 0xbf, 0x49, 0x6e, 0xb2, 0xcc, 0x68, 0x61, 0x78, 0x7d, 0x0a, 0xa6, 0x83, 0x30,
	0x3a, 0x07, 0xd2, 0xb7, 0xbd, 0x95, 0x36, 0x5b, 0xc3, 0x1a, 0x17, 0x14, 0x6f, 0x79, 0x1a, 0x41,
	0xb1, 0xb5, 0xd4, 0xcc, 0xb1, 0x8c, 0x2c, 0x2f, 0x75, 0x3f, 0xfd, 0x90, 0x64, 0x0f, 0xc6, 0xca,
	0xde, 0x74, 0xb8, 0x47, 0xbf, 0x73, 0xae, 0x10, 0xbc, 0x3e, 0x11, 0x3e, 0x2f, 0x39, 0x13, 0x6c,
	0x7e, 0x22, 0x3c, 0x54, 0x27, 0xe4, 0x9e, 0x08, 0xdf, 0x95, 0xfb, 0xb3, 0xb7, 0x07, 0xc6, 0x0e,
	0x39, 0xd5, 0xf3, 0x7d, 0xfd, 0x63, 0x4e, 0x8a, 0x46, 0x5b, 0xce, 0x46, 0x47, 0x52, 0x09, 0xda,
	0x5e, 0x08, 0x16, 0x00, 0x9b, 0xdd, 0x96, 0xf0, 0xdd, 0x96, 0x14, 0x02, 0x9d, 0x83, 0x2d, 0x9a,
	0x92, 0xfa, 0xc6, 0xd4, 0x98, 0x8d, 0x17, 0x5e, 0xa8, 0x69, 0xa1, 0x9c, 0xc7, 0x4d, 0x49, 0xb1,
	0x9a, 0x06, 0xb7, 0xd0, 0xd7, 0x77, 0x6e, 0x18, 0x1a, 0x83, 0x99, 0xa5, 0xca, 0x6f, 0x63, 0x33,
	0x4b, 0xd1, 0x05, 0xb8, 0x24, 0x11, 0x19, 0x2b, 0x7c, 0x73, 0x6a, 0xcc, 0x86, 0x8b, 0x49, 0xa8,
	0x9b, 0x84, 0x5d, 0x93, 0xf0, 0xaa, 0x68, 0x70, 0xeb, 0x09, 0x3e, 0x80, 0x1d, 0x53, 0x72, 0x44,
	0xef, 0xc0, 0xe1, 0x2c, 0xa7, 0x95, 0x6f, 0x4c, 0xad, 0xd9, 0x70, 0xf1, 0x2a, 0xd4, 0x1d, 0x65,
	0x36, 0x66, 0x39, 0xc5, 0x7a, 0x1a, 0x6c, 0x61, 0x20, 0x63, 0xd7, 0x44, 0x24, 0x0f, 0xff, 0x24,
	0x4f, 0xc0, 0x39, 0x92, 0x72, 0x95, 0xaa, 0x60, 0x07, 0x6b, 0x81, 0xce, 0xc1, 0xcd, 0x29, 0x39,
	0xd4, 0xd4, 0xb7, 0x14, 0x7a, 0xd4, 0xed, 0x24, 0x73, 0x71, 0x3b, 0x0b, 0xee, 0xc0, 0x8e, 0xb3,
	0xe4, 0xa7, 0x64, 0x64, 0x45, 0x4a, 0x1f, 0x15, 0xd6, 0xc1, 0x5a, 0xa0, 0x10, 0x7a, 0xba, 0x6f,
	0xe5, 0x9b, 0x0a, 0xf2, 0xfc, 0x52, 0x9d, 0x29, 0xf8, 0x08, 0xe3, 0x1b, 0x9a, 0x64, 0x47, 0x92,
	0x7f, 0xa3, 0x89, 0x60, 0xfc, 0x12, 0x8d, 0xc0, 0xd0, 0xcc, 0x01, 0x36, 0x1e, 0xa5, 0x6a, 0x54,
	0xcb, 0x01, 0x36, 0x1a, 0xa9, 0x9e, 0x7c, 0x4b, 0xab, 0xa7, 0xe0, 0x13, 0xd8, 0x6b, 0xf6, 0x8b,
	0x22, 0x0f, 0xac, 0xfa, 0xcf, 0x7a, 0xf2, 0x88, 0x2e, 0xc0, 0xa9, 0x4a, 0x4a, 0xd3, 0xf6, 0x61,
	0xdf, 0x74, 0x8b, 0xfc, 0x1d, 0x85, 0xb5, 0x29, 0xf8, 0x0e, 0xce, 0xe6, 0x81, 0x31, 0xf1, 0x0c,
	0x68, 0x02, 0x4e, 0x55, 0x97, 0x94, 0x2b, 0x50, 0x1f, 0x6b, 0x21, 0xf1, 0x25, 0xcb, 0x0a, 0xa1,
	0xaa, 0xfc, 0x07, 0xaf, 0x4c, 0xef, 0xbf, 0x40, 0xbf, 0xfb, 0x14, 0xa8, 0x07, 0x56, 0xb4, 0xba,
	0xf3, 0x5e, 0x20, 0x00, 0x77, 0x73, 0x7f, 0x7d, 0xbd, 0xc4, 0x9e, 0x81, 0x5e, 0xc2, 0xe0, 0x3e,
	0x5a, 0x6e, 0x57, 0x51, 0xb4, 0xc4, 0x9e, 0x89, 0xc6, 0x00, 0xf1, 0xf2, 0x6a, 0xdd, 0x6a, 0x0b,
	0x0d, 0xa1, 0x77, 0xfb, 0x35, 0x8a, 0x57, 0xd1, 0x67, 0xcf, 0xde, 0xbb, 0xea, 0x19, 0x2f, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x27, 0x77, 0xd1, 0xfc, 0xd2, 0x02, 0x00, 0x00,
}
