kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: think
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: think-secrets
  namespace: think # This only grants permissions within the "think" namespace.
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive. the default serviceAccount would be "default"
  namespace: think
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io