apiVersion: v1
kind: PersistentVolume
metadata:
  name: think-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/sdb
  nodeAffinity:
    required:
      nodeSelectorTerms: