apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: think
  labels:
    app: redis-master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
